### ISSUE TITLE
corrupting links without a language in the url

### ISSUE THREAD

**Issue by CennoxX** [Arasz/MicrosoftDocsLanguageChanger#2]
The add-on changes links that don't have a language part and corrupts them.

Example: https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process/?WT.mc_id=none-github-bramin leads to https://docs.microsoft.com/en-us/android/deploy-test/building-apps/build-process/

**Comment by Arasz** [comment]
@CennoxX Thanks for the pull request 👍
