### ISSUE TITLE
should support https://azure.microsoft.com/ too

### ISSUE THREAD

**Issue by Baspr** [Arasz/MicrosoftDocsLanguageChanger#4]
quite some information is in the https://azure.microsoft.com/ websites. These would also befefit from this extension.

**Comment by tejado** [comment]
This would be great! Is there any status about this enhancement?

**Comment by tejado** [comment]
Wouldn't it be possible to replace "docs" with a regex, e.g. \w+ in all the URL's? I guess this would be also the easiest solution.

**Comment by Arasz** [comment]
I think they moved all docs to docs subdomain now 🤔
