### ISSUE TITLE
Error 404 with URLs that contain /previous-versions/ instead of the language.

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [Arasz/MicrosoftDocsLanguageChanger#7]
See https://github.com/dotnet/docs/issues/14014

Example page: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/runtime-callable-wrapper

Links that work correctly:
https://docs.microsoft.com/en-us/dotnet/standard/native-interop/com-wrappers
https://docs.microsoft.com/en-us/dotnet/standard/native-interop/com-callable-wrapper
Links that do not work:
https://docs.microsoft.com/previous-versions/dotnet/netframework-4.0/k83zzh38(v=vs.100)
https://docs.microsoft.com/previous-versions/dotnet/netframework-4.0/h7hx9abd(v=vs.100)
https://docs.microsoft.com/previous-versions/dotnet/netframework-4.0/56kh4hy7(v=vs.100)

My guess is that the string **previous-versions** is interpreted as a language identifier and replaced with en-us. Those links probably have to stay unmodified.

**Comment by Arasz** [comment]
Thanks for the input, I fixed it in the current version.
